version: '3.7'
services:
  artifactory-1:
    image: releases-docker.jfrog.io/jfrog/artifactory-pro:${ARTIFACTORY_VERSION:-latest}
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"
    volumes:
      - ./artifactory.lic:/artifactory_extra_conf/artifactory.lic:ro # This file is not part of the repo. You need to provide this license file.
      - ./access.config.patch.yml:/opt/jfrog/artifactory/var/etc/access/access.config.patch.yml:ro # This file is not part of the repo. You need to provide this license file.

  artifactory-2:
    image: releases-docker.jfrog.io/jfrog/artifactory-pro:${ARTIFACTORY_VERSION:-latest}
    ports:
      - "9080:8080"
      - "9081:8081"
      - "9082:8082"
    volumes:
      - ./artifactory.lic:/artifactory_extra_conf/artifactory.lic:ro # This file is not part of the repo. You need to provide this license file.
